# Generated by Django 2.1.3 on 2018-11-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataviz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viz_id', models.CharField(max_length=8, unique=True, verbose_name='ID')),
                ('viz_name', models.CharField(max_length=100)),
                ('viz_verbose_name', models.CharField(default='---', max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('viz_description', models.TextField(default='A brief Description of the Viz')),
                ('viz_source', models.URLField(default='Viz Source')),
            ],
            options={
                'verbose_name': 'Dataviz',
                'verbose_name_plural': 'Datavizzes',
            },
        ),
    ]
