# Generated by Django 2.1.3 on 2018-11-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='women_congress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.TextField()),
                ('years', models.TextField()),
                ('women_total', models.IntegerField()),
                ('republican', models.IntegerField()),
                ('of_women_rep', models.FloatField(default='')),
                ('of_party_rep', models.FloatField(default='')),
                ('democratic', models.IntegerField()),
                ('of_women_dem', models.FloatField(default='')),
                ('of_party_dem', models.FloatField(default='')),
            ],
        ),
    ]
