# Generated by Django 2.1.4 on 2018-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0002_women_congress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
