# Generated by Django 2.1.4 on 2018-12-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0003_dataviz_viz_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='author',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_id',
            field=models.CharField(max_length=4, unique=True, verbose_name='ID'),
        ),
    ]
