# Generated by Django 2.1.4 on 2018-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0006_mlb_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='model',
            field=models.CharField(choices=[('mlb_beer', 'mlb_beer'), ('women_congress', 'women_congress')], max_length=200),
        ),
    ]
