# Generated by Django 2.1.4 on 2018-12-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0007_auto_20181205_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataviz',
            name='model',
        ),
        migrations.RemoveField(
            model_name='dataviz',
            name='viz_id',
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_name',
            field=models.CharField(choices=[('mlb_beer', 'mlb_beer'), ('women_congress', 'women_congress')], max_length=100),
        ),
    ]
