# Generated by Django 2.1.4 on 2018-12-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0008_auto_20181206_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLB_beers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('team', models.TextField()),
                ('nickname', models.TextField()),
                ('city', models.TextField()),
                ('price', models.FloatField(default='')),
                ('size', models.FloatField(default='')),
                ('price_per_ounce', models.FloatField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='mlb_beer',
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_name',
            field=models.CharField(choices=[('MLB_beers', 'MLB_beers'), ('mlb_beer', 'mlb_beer'), ('women_congress', 'women_congress')], max_length=100),
        ),
    ]
