# Generated by Django 2.1.4 on 2018-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0009_auto_20181217_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_name',
            field=models.CharField(choices=[('MLB_beers', 'MLB_beers'), ('women_congress', 'women_congress')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.ImageField(upload_to='vizzes/static/vizzes/images/'),
        ),
    ]
