# Generated by Django 2.1.4 on 2018-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0011_auto_20181218_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='viz_file',
            field=models.FileField(default='', upload_to='vizzes/static/vizzes/js'),
            preserve_default=False,
        ),
    ]
