# Generated by Django 2.1.4 on 2018-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0012_dataviz_viz_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.FileField(upload_to='vizzes/js'),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.ImageField(upload_to='vizzes/images/'),
        ),
    ]
