# Generated by Django 2.1.4 on 2018-12-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0013_auto_20181220_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.FileField(upload_to='vizzes/static/vizzes/js'),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.ImageField(upload_to='vizzes/static/vizzes/images'),
        ),
    ]
