# Generated by Django 2.1.4 on 2018-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0014_auto_20181220_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.URLField(default=''),
        ),
    ]
