# Generated by Django 2.1.4 on 2019-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0015_auto_20181221_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.URLField(default='JS file location', max_length=500),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_source',
            field=models.URLField(default='Data Source'),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.URLField(default='thumbnail for Viz Card'),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_verbose_name',
            field=models.CharField(default='---', max_length=500),
        ),
    ]
