# Generated by Django 2.1.4 on 2019-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0016_auto_20190208_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.URLField(default='https://cdn.jsdelivr.net/gh/jasparr77/d3/[Folder]/[JS File]', max_length=500),
        ),
    ]
