# Generated by Django 2.2 on 2019-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0017_auto_20190208_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='viz_type',
            field=models.CharField(choices=[('D3L', 'D3 w/ Scrollytelling'), ('D3T', 'Static D3'), ('TBX', 'Embedded Tableau Workbook'), ('IMG', 'Image'), ('WRD', 'Just Words')], default='D3T', max_length=3),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='viz_thumb',
            field=models.URLField(default='https://cdn.jsdelivr.net/gh/jasparr77/d3/[Folder]/[PNG File]'),
        ),
    ]
