# Generated by Django 2.2 on 2019-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0021_auto_20190502_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.TextField(default='Paste CDN URL or Tableau Workbook and sheet name (e.g., "workbook/sheetname") here', max_length=1000),
        ),
    ]
