# Generated by Django 2.2 on 2019-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizzes', '0022_auto_20190507_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='viz_file',
            field=models.CharField(default='Paste CDN URL or Tableau Workbook and sheet name (e.g., "workbook/sheetname") here', max_length=1000),
        ),
    ]
